language: node_js
sudo: false
dist: trusty

node_js:
 - 6.10.0

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --window-size=800,600

before_script:
  - npm install -g protractor
  - webdriver-manager update
  - npm install
  